debug: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


  datasource:
    name: crm
    url: jdbc:mysql://118.31.13.117:33306/crm?characterEncoding=UTF-8&userSSL=false&serverTimezone=UTC
    username: root
    password: beginnercong
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

server:
  servlet:
    context-path: /yf1804
  port: 8022
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapping/*.xml
  config-locations: classpath:config.xml
  type-aliases-package: com.zktr.crmproject.pojos
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  plugin: tk.mybatis.mapper.generator.MapperPlugin
  Mapper: tk.mybatis.mapper.common.Mappers
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

http:
  encoding:
    charset: UTF-8

#文件保存位置
uploadFile:
  resourceHandler: /uploadImgFiles/**   #请求 url 中的资源映射
  location: E:/PL/uploadImgFiles/ #自定义上传文件本地保存路径
