debug: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#  jackson:
#    #日期格式化
#    date-format: yyyy-MM-dd HH:mm:ss
#    serialization:
#      write-dates-as-timestamps: false
      #格式化输出
#      indent_output: true
#      #忽略无法转换的对象
#      fail_on_empty_beans: false
#    #设置空如何序列化
#    defaultPropertyInclusion: NON_EMPTY
#    deserialization:
#      #允许对象忽略json中不存在的属性
#      fail_on_unknown_properties: false
#    parser:
#      #允许出现特殊字符和转义符
#      allow_unquoted_control_chars: true
#      #允许出现单引号
#      allow_single_quotes: true

  datasource:
    name: crm
    url: jdbc:mysql://118.31.13.117:33306/crm?characterEncoding=UTF-8&userSSL=false&serverTimezone=UTC
    username: root
    password: beginnercong
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

server:
  servlet:
    context-path: /yf1804
  port: 8022
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapping/*.xml
  config-location: classpath:config.xml
  type-aliases-package: com.zktr.crmproject.pojos

mapper:
  plugin: tk.mybatis.mapper.generator.MapperPlugin
  Mapper: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

http:
  encoding:
    charset: UTF-8

#文件保存位置
uploadFile:
  resourceHandler: /uploadImgFiles/**   #请求 url 中的资源映射
  location: E:/PL/uploadImgFiles/ #自定义上传文件本地保存路径
